# **The Multivariate Gaussian**

The univariate normal distribution can be generalised to a d-dimensional space. The multivariate Gaussian distribution is used widely in statistics, machine learning, and Bayesian inference. The multivariate Gaussian distributionis defined by its **mean vector** and the **covariance matrix**.

$$
p(\mathbf{x}) = \frac{1}{(2\pi)^{d/2} |\boldsymbol{\Sigma}|^{1/2}} 
\exp \left( -\frac{1}{2} (\mathbf{x} - \boldsymbol{\mu})^T \boldsymbol{\Sigma}^{-1} (\mathbf{x} - \boldsymbol{\mu}) \right)
$$

where,
- $ \mathbf{x} \in \mathbb{R}^d$ : the d-dimensional random vector
- $\boldsymbol{\mu} \in \mathbb{R}^d$ : mean vector
    - $\mathbf{\mu} = E[x]$
- $\boldsymbol{\Sigma} \in \mathbb{R}^{d \times d}$ : covariance matrix
    - $\boldsymbol{\Sigma} = E[(\mathbf{x} - \mathbf{\mu})(\mathbf{x} - \mathbf{\mu})^T]$
    - The covariance between the $i^{th}$ and $j^{th}$ elements of $\mathbf{x}$ is $[\boldsymbol{\Sigma}]_{ij} = E[(x_i - \mu_i)(x_j - \mu_j)]$

### **How to sample from a multivariate Gaussian?**

Suppose we have a vector of samples from an N-dimensional standard normal distribution. This is easy to generate with standard number generators because elements of the sampled vector are not correlated.

$$
u \sim \mathcal{N} (0, I)
$$

$$
p(u) \propto \exp{(-0.5u^Tu)}
$$

Now let's take a matrix linear function of $u$:

$$
x = Mu + \mathbf{\mu}
$$

whose Jacobian matrix is

$$
J = \frac{dx}{du} = M
$$

where M is an invertible matrix, so we can write the inverse mapping:

$$
u = M^{-1} (x - \mathbf{\mu})
$$

We can use the vector change of variable formula to calculate the distribution of $x$. When we do this, we see that it gives a multivariate Gaussian with mean $\mathbf{\mu}$ and covariance matrix $MM^T$.

So, the recipe to sample from a multivariate Gaussian is:
1) Compute an M such that $\mathbf{\Sigma} = MM^T$ (using Cholesky decomposition)
2) Sample an N-dimensional vector $\mu \sim \mathcal{N} (0, I)$
3) Compute $x = Mu + \mathbf{\mu}$
4) $x$ is a random sample from $N(\mathbf{\mu}, \mathbf{\Sigma})$


In [35]:
import numpy as np

sigma = np.array([[4, 12, -16],
                  [12, 37, -43],
                  [-16, -43, 98]])

mu = np.array([1, 1, 2]).T
mu = np.reshape(mu, [3,1]) 

M = np.linalg.cholesky(sigma)

# Check sigma = MM^T
print(f' Check: \n {M @ np.transpose(M)}')

u = np.random.normal(size=(3,1))
print(f'Sample from multivariate Standard Normal:\n {u}')

x = M @ u + mu

print(f'Sample from multivariate Gaussian with mean mu and covariance matrix sigma:\n {x}')



 Check: 
 [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]
Sample from multivariate Standard Normal:
 [[-2.72924271]
 [ 0.45730286]
 [-0.39154607]]
Sample from multivariate Gaussian with mean mu and covariance matrix sigma:
 [[ -4.45848542]
 [-14.91815342]
 [ 24.94581777]]
